
#ifdef _foundation_defines
#else
#define Padd_b @"u_add_b"
#define Padd_br @"u_add_br"
#define Padd_y @"u_add_y"
#define Padd @"u_add"
#define Palbum_b @"u_album_b"
#define Palbum_g @"u_album_g"
#define Palbum_gray @"u_album_gray"
#define Palbum_y @"u_album_y"
#define Pcamora @"u_camora"
#define Pcard @"u_card_all"
#define PcardPhone @"u_card_phone"
#define PcardUnion @"u_card_union"
#define PcardUnionicon @"u_card_unionicon"
#define PcardVisa @"u_card_visa"
#define PcellDown_y @"u_cell_down_y"
#define PcellDown @"u_cell_down"
#define PcellLeft @"u_cell_left"
#define PcellLeftBig @"u_cell_left_gray"
#define PcellLeft_y @"u_cell_left_y"
#define PcellLeftA_y @"u_cell_leftArrow_y"
#define PcellLeftA @"u_cell_leftArrow"
#define PcellRight @"u_cell_right2"
#define PcellUp_y @"u_cell_up_y"
#define PcellUp @"u_cell_up"
#define Pclose_b @"u_close_b"
#define Pclose_gray @"u_close_gray"
#define Pclose @"u_close"
#define PcustomService_b @"u_custom_service_b"
#define PcustomService_y @"u_custom_service_y"
#define Pdelete @"u_delete_r"
#define Pdownload @"u_download"
#define PdownloadHL @"u_downloadHL"
#define Pequal @"u_equal"
#define Pfavorite @"u_favorite"
#define PfavoriteHL @"u_favorites"
#define PfrendsCircle @"u_frends_circle"
#define Pgiftbox @"u_giftbox_y"
#define Pgou_b @"u_gou_b"
#define Pgou_r @"u_gou_g_r"
#define Pgou_g @"u_gou_g"
#define Pgou_gray @"u_gou_gray"
#define Pheart @"u_heart_r"
#define Phistory @"u_history_y"
#define Phongbao @"u_hongbao_y"
#define Palipay @"u_icon_alipay_b"
#define Papple @"u_icon_apple"
#define Pappstore @"u_icon_appstore"
#define Pfrendcircle @"u_icon_frendcircle"
#define Pkugou @"u_icon_kugou"
#define PQQ @"u_icon_QQ"
#define Pqqzone @"u_icon_qqzone"
#define Psina @"u_icon_sina"
#define Pwechart @"u_icon_wechart"
#define Pnew @"u_label_new"
#define Plabels @"u_labels"
#define PmapLocation @"u_map_location"
#define PmyLocation @"u_map_mylocation"
#define PmapNavi @"u_map_navi"
#define PmessageAdd @"u_message_add"
#define PmessageAddHL @"u_message_addHL"
#define Pmessageb @"u_message_b"
#define Pmessagebg @"u_message_bg"
#define PmessageFace @"u_message_face"
#define PmessageFaceHL @"u_message_faceHL"
#define PmessageVoice @"u_message_HLvoice"
#define PmessageKeyboard @"u_message_keyboard"
#define PmessageKeyboardHL @"u_message_keyboardHL"
#define PmessageVoicek @"u_message_voicek"
#define PmessageVoicekHL @"u_message_voicekHL"
#define PmicGray @"u_mic_gray"
#define PmicYellow @"u_mic_yellow"
#define Pmusic @"u_music"
#define PmusicHL @"u_musicHL"
#define Pnavi3p_b @"u_navi_3p_b"
#define Pnavi3p_y @"u_navi_3p_y"
#define Pnavi_b @"u_navi_b"
#define Ppancel @"u_pancel"
#define PpayWechart @"u_pay_wecahrt"
#define PpersonAddy @"u_person_add_y1"
#define PpersonAdd @"u_person_add"
#define PpersonAddHL @"u_person_addHL"
#define Pperson_n @"u_person_n"
#define Pperson @"u_person"
#define PpersonHL @"u_personHL"
#define Ppicture @"u_picture"
#define Pprotect @"u_protect"
#define PprotectHL @"u_protectHL"
#define PQRCode @"u_QRCode"
#define Precord_y @"u_record_y"
#define Precord @"u_record"
#define ProcordHL @"u_recordHL"
#define Predpoint @"u_redpoint"
#define PreplyHL @"u_reply_HL"
#define Preply @"u_reply"
#define Pscan_b @"u_scan_b"
#define Pscan_round @"u_scan_round"
#define Pscan_y @"u_scan_y"
#define Pscan @"u_scan"
#define PscanQRCode @"u_ScanQRCode"
#define PscanQRCodeHL @"u_ScanQRCodeHL"
#define Psearch_gray @"u_search_gray"
#define Psearch_small @"u_search_small"
#define Psearch @"u_search"
#define Pseting @"u_seting"
#define PsetingHL @"u_settingHL"
#define PsexBoy @"u_sex_boy"
#define PsexBoy1 @"u_sex_boy1"
#define PsexGirl @"u_sex_girl"
#define PsexGirl1 @"u_sex_girl1"
#define Pshake @"u_Shake"
#define Pshok_b @"u_shok_b"
#define Pshok_g @"u_shok_g"
#define Pshok_r @"u_shok_r"
#define Pshok @"u_shok"
#define Psight @"u_sight"
#define Pstar @"u_star"
#define Ptop @"u_top"
#define Pvip @"u_vip"
#define Pvoice @"u_voice"
#define Pwallet @"u_wallet"
#define PwatchMV @"u_watch_mv"
#define Pzan @"u_zan_r"
#define Pwadd @"u_white_add"
#define PwaddFriend @"u_white_addfriend"
#define Pwbell @"u_white_bell"
#define Pwcall @"u_white_call"
#define Pwcamera @"u_white_camera"
#define PwcellLeft @"u_white_cell_left"
#define Pwcode @"u_white_code"
#define Pwfavourite @"u_white_favourite"
#define Pwhistory @"u_white_history"
#define Pwmore @"u_white_more"
#define Pwnavi @"u_white_navi"
#define Pwnewmessage @"u_white_newmessage"
#define Pwpeople @"u_white_people"
#define Pwperson @"u_white_person"
#define Pwscan @"u_white_scan"
#define Pwsearch @"u_white_search"
#define Pwseticon @"u_white_seticon"
#define Pwsetting @"u_white_setting"
#define Pwshot @"u_white_shot"
#define Pwstar @"u_white_star"
#define Pwvip @"u_white_vip"
#define Pwwifi @"u_white_wifi"
#define PuserLogo @"userLogo"



#define TableHeader 50
#define ShowImage_H 80
#define PlaceHolder @" "
#define offSet_X 20
#define EmotionItemPattern    @"\\[em:(\\d+):\\]"
#define kDistance 20 //说说和图片的间隔
#define kReplyBtnDistance 30 //回复按钮距离
#define kReply_FavourDistance 8 //回复按钮到点赞的距离
#define AttributedImageNameKey      @"ImageName"
#define screenWidth  [UIScreen mainScreen].bounds.size.width
#define screenHeight  [UIScreen mainScreen].bounds.size.height
#define limitline 4
#define kSelf_SelectedColor [UIColor colorWithWhite:0 alpha:0.4] //点击背景  颜色
#define kUserName_SelectedColor [UIColor colorWithWhite:0 alpha:0.25]//点击姓名颜色
#define DELAYEXECUTE(delayTime,func) (dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayTime * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{func;}))
#define kContentText1 @"思想不会流血，不会感到痛苦，思想不会死去"
#define kContentText2 @"这张面具之下，不是肉体，而是一种思想但思想是不怕子弹的"
#define kContentText3 @"Most people are so ungrateful to be alive. But not you. Not anymore. "
#define kContentText4 @"活着本来没有什么意义，但只要活着就会发现很多有趣的13688919929事，就像你发现了花，我又发现你一样[em:03:]。"
#define kContentText5 @"地狱的房间已满，于是，[em:02:][em:02:]死亡爬上了人间如果一个人觉得他自己死的很不值,就会把诅咒留在他生前接触过的地方[em:02:]只要有人经过这些地方[em:02:]就会被咒语套中如果一个人觉得他自己死的很不值,就会把诅咒留在他生前接触过的地方[em:02:]只要有人经过这些地方[em:02:]就会被咒语套中如果一个人觉得他自己死的很不值,就会把诅咒留在他生前接触过的地方[em:02:]只要有人经过这些地方[em:02:]就会被咒语套中如果一个人觉得他自己死的很不值,就会把诅咒留在他生前接触过的地方[em:02:]只要有人经过这些地方[em:02:]就会被咒语套中"
#define kContentText6 @"如果一个人觉得他自己死的很不值,就会把诅咒留在他生前接触过的地方[em:02:]只要有人经过这些地方[em:02:]就会被咒语套中"
#define kShuoshuoText1 @"驱魔人 “你可知道邪恶深藏于你心深处，但我会始终在你的[em:02:]左右，握着我的手，我会让你看到神迹，抱紧信仰，除此你一无所有！”"
#define kShuoshuoText2 @"李太啊，我的饺子最好吃，劲道、柔软、不露馅[em:03:]揉面的时候要一直揉到面团表面象剥了壳的鸡蛋，吃起来一包鲜汁"
#define kShuoshuoText3 @"如果晚上月亮升起的时候，月光www.baidu.com照到我的门口，我希望[em:03:]月光www.baidu.com女神能满足我一个愿望，我想要一双人类的手。我想用我的双手把我的爱人紧紧地拥在怀中，哪怕只有一次。如果我从来没有品尝过温暖的感觉，也许我不会这样寒冷；如果我从没有感受过爱情的甜美，我也许就不会这样地痛苦。如果我没有遇到善良的佩格，如果我从来不曾离开过我的房间，我就不会知道我原来是这样的孤独"
#define kShuoshuoText4 @"人有的时候很脆弱，会遇到很多不如意18618881888的事，日积月累就会形成心结，就算想告诉亲戚朋友，他们也未必懂得怎样[em:03:]开解"
#define kShuoshuoText5 @"如果是像金钱这种东西被抢走的话，再抢[em:03:]回来就好了！但如果是人性或温暖的心的话……那就只有遇上心中同样是空虚的人，才有www.baidu.com办法帮你填补起内心的空洞"
#define kShuoshuoText6 @"双目瞪人玛[em:03:]丽肖,傀儡为子常怀抱,汝辈小儿需切记,梦中遇她莫尖叫"
#endif
